/**
 * System Audit Log Mock Data for Retail Inventory Management System (Project ID: P_022)
 * Phase 2H: Administration & Audit Compliance
 * 
 * NOTE: Immutable operational audit trail records across modules, entities, and operators.
 */

export const INITIAL_AUDIT_LOGS = [
  {
    id: 'aud-101',
    timestamp: '2026-09-29 09:30:15',
    user: 'Alex Mercer',
    action: 'LOGIN',
    module: 'SYSTEM',
    entity: 'User Session',
    entityId: 'usr-1',
    description: 'Administrator logged into console from 192.168.1.42',
    severity: 'INFO',
  },
  {
    id: 'aud-102',
    timestamp: '2026-09-29 09:12:44',
    user: 'Neha Kapoor',
    action: 'STOCK_ADJUSTMENT',
    module: 'INVENTORY',
    entity: 'Inventory Item',
    entityId: 'inv-1',
    description: 'Physical audit adjustment: +10 units added for Apple iPhone 15 at Delhi Hub',
    severity: 'INFO',
  },
  {
    id: 'aud-103',
    timestamp: '2026-09-29 08:45:20',
    user: 'Vikram Malhotra',
    action: 'APPROVAL',
    module: 'PURCHASE_ORDER',
    entity: 'Purchase Order',
    entityId: 'po-3',
    description: 'Approved PO-2026-0034 for Prime Computing Solutions (₹11,09,200)',
    severity: 'SUCCESS',
  },
  {
    id: 'aud-104',
    timestamp: '2026-09-29 07:15:02',
    user: 'Amit Sharma',
    action: 'STATUS_CHANGE',
    module: 'ORDER',
    entity: 'Customer Order',
    entityId: 'ord-1004',
    description: 'Progressed order ORD-2026-0071 stage to PICKING at Pune Hub',
    severity: 'INFO',
  },
  {
    id: 'aud-105',
    timestamp: '2026-09-28 17:35:10',
    user: 'Priya Deshmukh',
    action: 'STATUS_CHANGE',
    module: 'ORDER',
    entity: 'Customer Order',
    entityId: 'ord-1002',
    description: 'Dispatched and shipped ORD-2026-0052 with Bluedart Tracking #BD88921',
    severity: 'SUCCESS',
  },
  {
    id: 'aud-106',
    timestamp: '2026-09-28 16:20:45',
    user: 'Ramesh Kumar',
    action: 'CREATE',
    module: 'INVENTORY',
    entity: 'Stock Movement',
    entityId: 'mov-1001',
    description: 'Recorded inbound goods receipt for PO-2026-0012 (+20 units)',
    severity: 'SUCCESS',
  },
  {
    id: 'aud-107',
    timestamp: '2026-09-28 15:10:00',
    user: 'Sunil Verma',
    action: 'CREATE',
    module: 'ORDER',
    entity: 'Customer Order',
    entityId: 'ord-1007',
    description: 'Created customer sales order ORD-2026-0103 for ₹87,900',
    severity: 'INFO',
  },
  {
    id: 'aud-108',
    timestamp: '2026-09-28 14:05:32',
    user: 'Vikram Malhotra',
    action: 'CREATE',
    module: 'PURCHASE_ORDER',
    entity: 'Purchase Order',
    entityId: 'po-12',
    description: 'Generated PO-2026-0128 for Galaxy Distribution Networks (₹12,12,450)',
    severity: 'INFO',
  },
  {
    id: 'aud-109',
    timestamp: '2026-09-28 11:40:18',
    user: 'Alex Mercer',
    action: 'STATUS_CHANGE',
    module: 'USER',
    entity: 'User Account',
    entityId: 'usr-8',
    description: 'Deactivated user account for Kavita Chawla due to leave of absence',
    severity: 'WARNING',
  },
  {
    id: 'aud-110',
    timestamp: '2026-09-27 18:25:00',
    user: 'Neha Kapoor',
    action: 'UPDATE',
    module: 'PRODUCT',
    entity: 'Catalog Product',
    entityId: 'prod-102',
    description: 'Updated cost price and reorder threshold for Samsung Galaxy S25',
    severity: 'INFO',
  },
  {
    id: 'aud-111',
    timestamp: '2026-09-27 14:15:22',
    user: 'Sunil Verma',
    action: 'STATUS_CHANGE',
    module: 'ORDER',
    entity: 'Customer Order',
    entityId: 'ord-1010',
    description: 'Cancelled order ORD-2026-0136 upon customer refund request; reservation released',
    severity: 'WARNING',
  },
  {
    id: 'aud-112',
    timestamp: '2026-09-27 10:30:40',
    user: 'Alex Mercer',
    action: 'CREATE',
    module: 'SUPPLIER',
    entity: 'Vendor Partner',
    entityId: 'sup-7',
    description: 'Onboarded Horizon Smart Peripherals (SUP-DEL-007) with Net 60 terms',
    severity: 'INFO',
  },
  {
    id: 'aud-113',
    timestamp: '2026-09-26 16:50:11',
    user: 'Amit Sharma',
    action: 'STATUS_CHANGE',
    module: 'WAREHOUSE',
    entity: 'Storage Facility',
    entityId: 'wh-6',
    description: 'Toggled Jaipur Regional Warehouse operational status to INACTIVE for maintenance',
    severity: 'WARNING',
  },
  {
    id: 'aud-114',
    timestamp: '2026-09-26 13:22:05',
    user: 'Vikram Malhotra',
    action: 'STATUS_CHANGE',
    module: 'PURCHASE_ORDER',
    entity: 'Purchase Order',
    entityId: 'po-8',
    description: 'Cancelled PO-2026-0089 due to vendor credit review hold',
    severity: 'WARNING',
  },
  {
    id: 'aud-115',
    timestamp: '2026-09-25 17:00:00',
    user: 'Ramesh Kumar',
    action: 'STOCK_ADJUSTMENT',
    module: 'INVENTORY',
    entity: 'Inventory Allocation',
    entityId: 'inv-3',
    description: 'Damaged stock deduction: -5 units written off for Dell Inspiron 15 at Delhi Hub',
    severity: 'WARNING',
  },
  {
    id: 'aud-116',
    timestamp: '2026-09-25 11:15:30',
    user: 'Alex Mercer',
    action: 'CREATE',
    module: 'USER',
    entity: 'User Account',
    entityId: 'usr-7',
    description: 'Provisioned new staff account for Ramesh Kumar in Inbound Logistics',
    severity: 'INFO',
  },
  {
    id: 'aud-117',
    timestamp: '2026-09-24 16:40:12',
    user: 'Sunil Verma',
    action: 'STATUS_CHANGE',
    module: 'ORDER',
    entity: 'Customer Order',
    entityId: 'ord-1001',
    description: 'Confirmed delivery completion for customer order ORD-2026-0048',
    severity: 'SUCCESS',
  },
  {
    id: 'aud-118',
    timestamp: '2026-09-24 14:10:00',
    user: 'Neha Kapoor',
    action: 'CREATE',
    module: 'PRODUCT',
    entity: 'Catalog Product',
    entityId: 'prod-112',
    description: 'Added Bajaj DX-7 1000W Dry Iron to Home Appliances catalog',
    severity: 'INFO',
  },
  {
    id: 'aud-119',
    timestamp: '2026-09-23 18:00:25',
    user: 'Alex Mercer',
    action: 'UPDATE',
    module: 'SYSTEM',
    entity: 'System Parameters',
    entityId: 'cfg-tax',
    description: 'Standard merchandise GST tax schedule verified at 18%',
    severity: 'INFO',
  },
  {
    id: 'aud-120',
    timestamp: '2026-09-23 12:30:00',
    user: 'Vikram Malhotra',
    action: 'APPROVAL',
    module: 'PURCHASE_ORDER',
    entity: 'Purchase Order',
    entityId: 'po-1',
    description: 'Approved PO-2026-0012 for Apex ElectroTech India (₹14,63,200)',
    severity: 'SUCCESS',
  },
];
