/**
 * Calculates stock status based on current stock and reorder threshold.
 */
export function calculateStockStatus(currentStock, reorderLevel) {
  const stock = parseInt(currentStock, 10) || 0;
  const reorder = parseInt(reorderLevel, 10) || 0;

  if (stock === 0) return 'OUT_OF_STOCK';
  if (stock <= reorder) return 'LOW_STOCK';
  return 'IN_STOCK';
}

export const INITIAL_INVENTORY = [
  {
    id: 'inv-1',
    productId: 'prod-101',
    warehouseId: 'wh-1',
    productName: 'Apple iPhone 15 (128 GB) - Black',
    sku: 'SKU-APL-IP15',
    category: 'Electronics',
    warehouseName: 'Delhi Central Hub',
    warehouseCode: 'WH-DEL-001',
    currentStock: 120,
    reservedStock: 25,
    availableStock: 95,
    reorderLevel: 40,
    stockStatus: 'IN_STOCK',
    lastMovement: 'RECEIPT +50',
    lastUpdated: '2026-09-28',
  },
  {
    id: 'inv-2',
    productId: 'prod-101',
    warehouseId: 'wh-2',
    productName: 'Apple iPhone 15 (128 GB) - Black',
    sku: 'SKU-APL-IP15',
    category: 'Electronics',
    warehouseName: 'Mumbai Distribution Center',
    warehouseCode: 'WH-MUM-001',
    currentStock: 85,
    reservedStock: 15,
    availableStock: 70,
    reorderLevel: 30,
    stockStatus: 'IN_STOCK',
    lastMovement: 'SALE -12',
    lastUpdated: '2026-09-27',
  },
  {
    id: 'inv-3',
    productId: 'prod-101',
    warehouseId: 'wh-3',
    productName: 'Apple iPhone 15 (128 GB) - Black',
    sku: 'SKU-APL-IP15',
    category: 'Electronics',
    warehouseName: 'Bangalore Fulfillment Hub',
    warehouseCode: 'WH-BLR-001',
    currentStock: 18,
    reservedStock: 5,
    availableStock: 13,
    reorderLevel: 25,
    stockStatus: 'LOW_STOCK',
    lastMovement: 'SALE -6',
    lastUpdated: '2026-09-28',
  },
  {
    id: 'inv-4',
    productId: 'prod-102',
    warehouseId: 'wh-1',
    productName: 'Samsung Galaxy S25 5G (256 GB) - Titanium Gray',
    sku: 'SKU-SAM-S25',
    category: 'Electronics',
    warehouseName: 'Delhi Central Hub',
    warehouseCode: 'WH-DEL-001',
    currentStock: 90,
    reservedStock: 20,
    availableStock: 70,
    reorderLevel: 35,
    stockStatus: 'IN_STOCK',
    lastMovement: 'RECEIPT +40',
    lastUpdated: '2026-09-26',
  },
  {
    id: 'inv-5',
    productId: 'prod-102',
    warehouseId: 'wh-2',
    productName: 'Samsung Galaxy S25 5G (256 GB) - Titanium Gray',
    sku: 'SKU-SAM-S25',
    category: 'Electronics',
    warehouseName: 'Mumbai Distribution Center',
    warehouseCode: 'WH-MUM-001',
    currentStock: 65,
    reservedStock: 10,
    availableStock: 55,
    reorderLevel: 30,
    stockStatus: 'IN_STOCK',
    lastMovement: 'TRANSFER_IN +15',
    lastUpdated: '2026-09-27',
  },
  {
    id: 'inv-6',
    productId: 'prod-102',
    warehouseId: 'wh-4',
    productName: 'Samsung Galaxy S25 5G (256 GB) - Titanium Gray',
    sku: 'SKU-SAM-S25',
    category: 'Electronics',
    warehouseName: 'Hyderabad Warehouse',
    warehouseCode: 'WH-HYD-001',
    currentStock: 12,
    reservedStock: 4,
    availableStock: 8,
    reorderLevel: 20,
    stockStatus: 'LOW_STOCK',
    lastMovement: 'SALE -4',
    lastUpdated: '2026-09-25',
  },
  {
    id: 'inv-7',
    productId: 'prod-103',
    warehouseId: 'wh-1',
    productName: 'Dell Inspiron 15 Laptop (Intel Core i5, 16GB)',
    sku: 'SKU-DEL-IN15',
    category: 'Electronics',
    warehouseName: 'Delhi Central Hub',
    warehouseCode: 'WH-DEL-001',
    currentStock: 28,
    reservedStock: 6,
    availableStock: 22,
    reorderLevel: 20,
    stockStatus: 'IN_STOCK',
    lastMovement: 'ADJUSTMENT +2',
    lastUpdated: '2026-09-28',
  },
  {
    id: 'inv-8',
    productId: 'prod-103',
    warehouseId: 'wh-5',
    productName: 'Dell Inspiron 15 Laptop (Intel Core i5, 16GB)',
    sku: 'SKU-DEL-IN15',
    category: 'Electronics',
    warehouseName: 'Pune Regional Warehouse',
    warehouseCode: 'WH-PUN-001',
    currentStock: 8,
    reservedStock: 3,
    availableStock: 5,
    reorderLevel: 15,
    stockStatus: 'LOW_STOCK',
    lastMovement: 'SALE -3',
    lastUpdated: '2026-09-24',
  },
  {
    id: 'inv-9',
    productId: 'prod-103',
    warehouseId: 'wh-3',
    productName: 'Dell Inspiron 15 Laptop (Intel Core i5, 16GB)',
    sku: 'SKU-DEL-IN15',
    category: 'Electronics',
    warehouseName: 'Bangalore Fulfillment Hub',
    warehouseCode: 'WH-BLR-001',
    currentStock: 0,
    reservedStock: 0,
    availableStock: 0,
    reorderLevel: 15,
    stockStatus: 'OUT_OF_STOCK',
    lastMovement: 'SALE -5',
    lastUpdated: '2026-09-22',
  },
  {
    id: 'inv-10',
    productId: 'prod-104',
    warehouseId: 'wh-1',
    productName: 'OnePlus 12R 5G (Cool Blue, 16GB RAM)',
    sku: 'SKU-OP-12R',
    category: 'Electronics',
    warehouseName: 'Delhi Central Hub',
    warehouseCode: 'WH-DEL-001',
    currentStock: 40,
    reservedStock: 8,
    availableStock: 32,
    reorderLevel: 25,
    stockStatus: 'IN_STOCK',
    lastMovement: 'RECEIPT +30',
    lastUpdated: '2026-09-28',
  },
  {
    id: 'inv-11',
    productId: 'prod-104',
    warehouseId: 'wh-2',
    productName: 'OnePlus 12R 5G (Cool Blue, 16GB RAM)',
    sku: 'SKU-OP-12R',
    category: 'Electronics',
    warehouseName: 'Mumbai Distribution Center',
    warehouseCode: 'WH-MUM-001',
    currentStock: 0,
    reservedStock: 0,
    availableStock: 0,
    reorderLevel: 20,
    stockStatus: 'OUT_OF_STOCK',
    lastMovement: 'SALE -8',
    lastUpdated: '2026-09-20',
  },
  {
    id: 'inv-12',
    productId: 'prod-104',
    warehouseId: 'wh-6',
    productName: 'OnePlus 12R 5G (Cool Blue, 16GB RAM)',
    sku: 'SKU-OP-12R',
    category: 'Electronics',
    warehouseName: 'Jaipur Regional Warehouse',
    warehouseCode: 'WH-JAI-001',
    currentStock: 6,
    reservedStock: 1,
    availableStock: 5,
    reorderLevel: 15,
    stockStatus: 'LOW_STOCK',
    lastMovement: 'RETURN +1',
    lastUpdated: '2026-09-26',
  },
  {
    id: 'inv-13',
    productId: 'prod-105',
    warehouseId: 'wh-1',
    productName: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    sku: 'SKU-SNY-1000XM5',
    category: 'Accessories',
    warehouseName: 'Delhi Central Hub',
    warehouseCode: 'WH-DEL-001',
    currentStock: 75,
    reservedStock: 12,
    availableStock: 63,
    reorderLevel: 25,
    stockStatus: 'IN_STOCK',
    lastMovement: 'RECEIPT +35',
    lastUpdated: '2026-09-27',
  },
  {
    id: 'inv-14',
    productId: 'prod-105',
    warehouseId: 'wh-3',
    productName: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    sku: 'SKU-SNY-1000XM5',
    category: 'Accessories',
    warehouseName: 'Bangalore Fulfillment Hub',
    warehouseCode: 'WH-BLR-001',
    currentStock: 50,
    reservedStock: 8,
    availableStock: 42,
    reorderLevel: 20,
    stockStatus: 'IN_STOCK',
    lastMovement: 'TRANSFER_IN +20',
    lastUpdated: '2026-09-28',
  },
  {
    id: 'inv-15',
    productId: 'prod-106',
    warehouseId: 'wh-2',
    productName: 'Logitech MX Master 3S Wireless Performance Mouse',
    sku: 'SKU-LOG-MX3S',
    category: 'Accessories',
    warehouseName: 'Mumbai Distribution Center',
    warehouseCode: 'WH-MUM-001',
    currentStock: 45,
    reservedStock: 6,
    availableStock: 39,
    reorderLevel: 20,
    stockStatus: 'IN_STOCK',
    lastMovement: 'SALE -4',
    lastUpdated: '2026-09-27',
  },
  {
    id: 'inv-16',
    productId: 'prod-106',
    warehouseId: 'wh-5',
    productName: 'Logitech MX Master 3S Wireless Performance Mouse',
    sku: 'SKU-LOG-MX3S',
    category: 'Accessories',
    warehouseName: 'Pune Regional Warehouse',
    warehouseCode: 'WH-PUN-001',
    currentStock: 7,
    reservedStock: 2,
    availableStock: 5,
    reorderLevel: 15,
    stockStatus: 'LOW_STOCK',
    lastMovement: 'SALE -2',
    lastUpdated: '2026-09-25',
  },
  {
    id: 'inv-17',
    productId: 'prod-107',
    warehouseId: 'wh-1',
    productName: 'boAt Rockerz 450 Bluetooth On-Ear Headphones',
    sku: 'SKU-BOT-R450',
    category: 'Accessories',
    warehouseName: 'Delhi Central Hub',
    warehouseCode: 'WH-DEL-001',
    currentStock: 180,
    reservedStock: 30,
    availableStock: 150,
    reorderLevel: 50,
    stockStatus: 'IN_STOCK',
    lastMovement: 'RECEIPT +100',
    lastUpdated: '2026-09-28',
  },
  {
    id: 'inv-18',
    productId: 'prod-107',
    warehouseId: 'wh-4',
    productName: 'boAt Rockerz 450 Bluetooth On-Ear Headphones',
    sku: 'SKU-BOT-R450',
    category: 'Accessories',
    warehouseName: 'Hyderabad Warehouse',
    warehouseCode: 'WH-HYD-001',
    currentStock: 110,
    reservedStock: 15,
    availableStock: 95,
    reorderLevel: 40,
    stockStatus: 'IN_STOCK',
    lastMovement: 'SALE -14',
    lastUpdated: '2026-09-26',
  },
  {
    id: 'inv-19',
    productId: 'prod-108',
    warehouseId: 'wh-2',
    productName: "Levi's 511 Slim Fit Men's Denim Jeans",
    sku: 'SKU-LEV-511SL',
    category: 'Clothing',
    warehouseName: 'Mumbai Distribution Center',
    warehouseCode: 'WH-MUM-001',
    currentStock: 140,
    reservedStock: 20,
    availableStock: 120,
    reorderLevel: 40,
    stockStatus: 'IN_STOCK',
    lastMovement: 'RECEIPT +60',
    lastUpdated: '2026-09-25',
  },
  {
    id: 'inv-20',
    productId: 'prod-109',
    warehouseId: 'wh-3',
    productName: "Allen Solly Men's Regular Fit Cotton Casual Shirt",
    sku: 'SKU-ALS-CSH01',
    category: 'Clothing',
    warehouseName: 'Bangalore Fulfillment Hub',
    warehouseCode: 'WH-BLR-001',
    currentStock: 60,
    reservedStock: 10,
    availableStock: 50,
    reorderLevel: 30,
    stockStatus: 'IN_STOCK',
    lastMovement: 'SALE -10',
    lastUpdated: '2026-09-27',
  },
  {
    id: 'inv-21',
    productId: 'prod-110',
    warehouseId: 'wh-1',
    productName: 'Philips Essential Air Fryer (4.1L, 1400W)',
    sku: 'SKU-PHL-AF9200',
    category: 'Home Appliances',
    warehouseName: 'Delhi Central Hub',
    warehouseCode: 'WH-DEL-001',
    currentStock: 0,
    reservedStock: 0,
    availableStock: 0,
    reorderLevel: 25,
    stockStatus: 'OUT_OF_STOCK',
    lastMovement: 'SALE -15',
    lastUpdated: '2026-09-21',
  },
  {
    id: 'inv-22',
    productId: 'prod-110',
    warehouseId: 'wh-2',
    productName: 'Philips Essential Air Fryer (4.1L, 1400W)',
    sku: 'SKU-PHL-AF9200',
    category: 'Home Appliances',
    warehouseName: 'Mumbai Distribution Center',
    warehouseCode: 'WH-MUM-001',
    currentStock: 35,
    reservedStock: 5,
    availableStock: 30,
    reorderLevel: 20,
    stockStatus: 'IN_STOCK',
    lastMovement: 'TRANSFER_IN +10',
    lastUpdated: '2026-09-28',
  },
];
