/**
 * Notification Mock Data for Retail Inventory Management System (Project ID: P_022)
 * Phase 2G: Notifications & System Alerting
 * 
 * NOTE: Realistic operational alerts across inventory thresholds, purchase orders,
 * sales orders, warehouse capacity limits, and system maintenance.
 */

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif-1',
    type: 'LOW_STOCK',
    title: 'Low Stock Alert: iPhone 15 at Delhi Hub',
    message: 'Stock on hand for Apple iPhone 15 at Delhi Central Hub has dropped to 20 units (Reorder threshold: 40).',
    timestamp: '10 mins ago',
    read: false,
    severity: 'WARNING',
    relatedId: '/inventory/inv-1',
  },
  {
    id: 'notif-2',
    type: 'PURCHASE_ORDER',
    title: 'Purchase Order Approved',
    message: 'PO-2026-0034 for Dell Inspiron 15 laptops has been approved by the procurement manager.',
    timestamp: '45 mins ago',
    read: false,
    severity: 'SUCCESS',
    relatedId: '/purchase-orders/po-3',
  },
  {
    id: 'notif-3',
    type: 'ORDER',
    title: 'New High-Value Sales Order',
    message: 'Customer order ORD-2026-0052 worth ₹1,17,800 received for Mumbai Distribution Center.',
    timestamp: '2 hours ago',
    read: false,
    severity: 'INFO',
    relatedId: '/orders/ord-1002',
  },
  {
    id: 'notif-4',
    type: 'OUT_OF_STOCK',
    title: 'Out of Stock: Air Fryer at Jaipur Hub',
    message: 'Philips Essential Air Fryer is completely out of stock at Jaipur Regional Warehouse.',
    timestamp: '3 hours ago',
    read: false,
    severity: 'CRITICAL',
    relatedId: '/inventory',
  },
  {
    id: 'notif-5',
    type: 'WAREHOUSE',
    title: 'Warehouse Capacity Alert (85%)',
    message: 'Mumbai Distribution Center has reached 85% volumetric storage utilization (38,200 / 45,000 units).',
    timestamp: '5 hours ago',
    read: true,
    severity: 'WARNING',
    relatedId: '/inventory/warehouse/wh-2',
  },
  {
    id: 'notif-6',
    type: 'PURCHASE_ORDER',
    title: 'Inbound PO Goods Received',
    message: 'Goods receipt confirmed for PO-2026-0012. 20 units added to Delhi Central Hub inventory.',
    timestamp: '1 day ago',
    read: true,
    severity: 'SUCCESS',
    relatedId: '/purchase-orders/po-1',
  },
  {
    id: 'notif-7',
    type: 'ORDER',
    title: 'Order Dispatch Confirmed',
    message: 'Order ORD-2026-0048 has been marked as shipped with Bluedart courier tracking #BD88921.',
    timestamp: '1 day ago',
    read: true,
    severity: 'INFO',
    relatedId: '/orders/ord-1001',
  },
  {
    id: 'notif-8',
    type: 'LOW_STOCK',
    title: 'Low Stock Alert: boAt Earbuds at Pune Hub',
    message: 'boAt Airdopes 141 reached 25 units at Pune Regional Warehouse (Threshold: 50).',
    timestamp: '2 days ago',
    read: true,
    severity: 'WARNING',
    relatedId: '/inventory',
  },
  {
    id: 'notif-9',
    type: 'SYSTEM',
    title: 'Catalog Price Update Logged',
    message: 'Wholesale cost price modified for Samsung Galaxy S25 by Inventory Supervisor.',
    timestamp: '2 days ago',
    read: true,
    severity: 'INFO',
    relatedId: '/products/prod-102',
  },
  {
    id: 'notif-10',
    type: 'ORDER',
    title: 'Order Cancellation Handled',
    message: 'Order ORD-2026-0136 cancelled. 1 reserved unit released to free available stock.',
    timestamp: '3 days ago',
    read: true,
    severity: 'INFO',
    relatedId: '/orders/ord-1010',
  },
  {
    id: 'notif-11',
    type: 'WAREHOUSE',
    title: 'New Storage Facility Commissioned',
    message: 'Jaipur Regional Warehouse (WH-JAI-001) successfully registered in system.',
    timestamp: '4 days ago',
    read: true,
    severity: 'SUCCESS',
    relatedId: '/warehouses/wh-6',
  },
  {
    id: 'notif-12',
    type: 'SYSTEM',
    title: 'Scheduled Audit Complete',
    message: 'Monthly physical cycle count reconciliation report generated for Q3.',
    timestamp: '5 days ago',
    read: true,
    severity: 'INFO',
    relatedId: '/reports',
  },
];
