/**
 * Customer Order Mock Data for Retail Inventory Management System (Project ID: P_022)
 * Phase 2F: Customer Order Management & Fulfillment Operations
 * 
 * NOTE: Realistic Indian customer orders, addresses, fulfillment routes, and payment states.
 */

export const INITIAL_ORDERS = [
  {
    id: 'ord-1001',
    orderNumber: 'ORD-2026-0048',
    customerName: 'Aditya Sharma',
    customerEmail: 'aditya.sharma@gmail.com',
    customerPhone: '+91 98101 55443',
    orderDate: '2026-09-24',
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    totalAmount: 74900,
    warehouseId: 'wh-1',
    warehouseName: 'Delhi Central Hub',
    shippingAddress: {
      address: 'Flat 402, Lotus Apartments, Sector 45',
      city: 'Gurugram',
      state: 'Haryana',
      pincode: '122003',
    },
    items: [
      {
        productId: 'prod-101',
        productName: 'Apple iPhone 15 (128 GB) - Black',
        sku: 'SKU-APL-IP15',
        quantity: 1,
        unitPrice: 74900,
        total: 74900,
      },
    ],
    createdAt: '2026-09-24',
  },
  {
    id: 'ord-1002',
    orderNumber: 'ORD-2026-0052',
    customerName: 'Meera Iyer',
    customerEmail: 'meera.iyer@yahoo.co.in',
    customerPhone: '+91 98204 88776',
    orderDate: '2026-09-25',
    status: 'SHIPPED',
    paymentStatus: 'PAID',
    totalAmount: 117800,
    warehouseId: 'wh-2',
    warehouseName: 'Mumbai Distribution Center',
    shippingAddress: {
      address: '12B, Samudra Mahal, Worli Sea Face',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400018',
    },
    items: [
      {
        productId: 'prod-102',
        productName: 'Samsung Galaxy S25 5G (256 GB) - Titanium Gray',
        sku: 'SKU-SAM-S25',
        quantity: 1,
        unitPrice: 87900,
        total: 87900,
      },
      {
        productId: 'prod-104',
        productName: 'Sony WH-1000XM5 Wireless Headphones',
        sku: 'SKU-SNY-1000XM5',
        quantity: 1,
        unitPrice: 29900,
        total: 29900,
      },
    ],
    createdAt: '2026-09-25',
  },
  {
    id: 'ord-1003',
    orderNumber: 'ORD-2026-0065',
    customerName: 'Rohan Deshmukh',
    customerEmail: 'rohan.d@rediffmail.com',
    customerPhone: '+91 98450 33221',
    orderDate: '2026-09-26',
    status: 'PACKED',
    paymentStatus: 'PAID',
    totalAmount: 58999,
    warehouseId: 'wh-3',
    warehouseName: 'Bangalore Fulfillment Hub',
    shippingAddress: {
      address: 'House 88, 4th Main, Indiranagar',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560038',
    },
    items: [
      {
        productId: 'prod-103',
        productName: 'Dell Inspiron 15 Laptop (Intel Core i5, 16GB)',
        sku: 'SKU-DEL-IN15',
        quantity: 1,
        unitPrice: 58999,
        total: 58999,
      },
    ],
    createdAt: '2026-09-26',
  },
  {
    id: 'ord-1004',
    orderNumber: 'ORD-2026-0071',
    customerName: 'Sneha Patel',
    customerEmail: 'sneha.patel@gmail.com',
    customerPhone: '+91 97652 44332',
    orderDate: '2026-09-26',
    status: 'PICKING',
    paymentStatus: 'PAID',
    totalAmount: 43999,
    warehouseId: 'wh-5',
    warehouseName: 'Pune Regional Warehouse',
    shippingAddress: {
      address: 'Rowhouse 4, Silver Birch Society, Aundh',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411007',
    },
    items: [
      {
        productId: 'prod-106',
        productName: 'OnePlus 12R 5G (Cool Blue, 16GB RAM, 256GB)',
        sku: 'SKU-OP-12R',
        quantity: 1,
        unitPrice: 41999,
        total: 41999,
      },
      {
        productId: 'prod-107',
        productName: 'boAt Airdopes 141 True Wireless Earbuds',
        sku: 'SKU-BOAT-AD141',
        quantity: 1,
        unitPrice: 1999,
        total: 1999,
      },
    ],
    createdAt: '2026-09-26',
  },
  {
    id: 'ord-1005',
    orderNumber: 'ORD-2026-0082',
    customerName: 'Vikram Joshi',
    customerEmail: 'vjoshi@outlook.com',
    customerPhone: '+91 98492 11998',
    orderDate: '2026-09-27',
    status: 'PROCESSING',
    paymentStatus: 'PAID',
    totalAmount: 11998,
    warehouseId: 'wh-4',
    warehouseName: 'Hyderabad Warehouse',
    shippingAddress: {
      address: 'Plot 45, Jubilee Hills, Road No. 36',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500033',
    },
    items: [
      {
        productId: 'prod-108',
        productName: 'Logitech MX Master 3S Wireless Mouse',
        sku: 'SKU-LOGI-MXM3S',
        quantity: 1,
        unitPrice: 9999,
        total: 9999,
      },
      {
        productId: 'prod-107',
        productName: 'boAt Airdopes 141 True Wireless Earbuds',
        sku: 'SKU-BOAT-AD141',
        quantity: 1,
        unitPrice: 1999,
        total: 1999,
      },
    ],
    createdAt: '2026-09-27',
  },
  {
    id: 'ord-1006',
    orderNumber: 'ORD-2026-0094',
    customerName: 'Kavita Sundaram',
    customerEmail: 'kavita.s@gmail.com',
    customerPhone: '+91 94141 77665',
    orderDate: '2026-09-27',
    status: 'CONFIRMED',
    paymentStatus: 'PAID',
    totalAmount: 9499,
    warehouseId: 'wh-1',
    warehouseName: 'Delhi Central Hub',
    shippingAddress: {
      address: 'C-28, Kailash Colony',
      city: 'New Delhi',
      state: 'Delhi',
      pincode: '110048',
    },
    items: [
      {
        productId: 'prod-105',
        productName: 'Philips Essential Air Fryer (4.1L, 1400W)',
        sku: 'SKU-PHL-AF9200',
        quantity: 1,
        unitPrice: 7999,
        total: 7999,
      },
      {
        productId: 'prod-112',
        productName: 'Bajaj DX-7 1000W Dry Iron',
        sku: 'SKU-BAJ-IRON-DX7',
        quantity: 1,
        unitPrice: 1500,
        total: 1500,
      },
    ],
    createdAt: '2026-09-27',
  },
  {
    id: 'ord-1007',
    orderNumber: 'ORD-2026-0103',
    customerName: 'Nitin Singhania',
    customerEmail: 'nitin.singh@corp.in',
    customerPhone: '+91 98115 66554',
    orderDate: '2026-09-28',
    status: 'PENDING',
    paymentStatus: 'PENDING',
    totalAmount: 87900,
    warehouseId: 'wh-1',
    warehouseName: 'Delhi Central Hub',
    shippingAddress: {
      address: 'Tower 3, Penthouse 18, Golf Course Road',
      city: 'Gurugram',
      state: 'Haryana',
      pincode: '122002',
    },
    items: [
      {
        productId: 'prod-102',
        productName: 'Samsung Galaxy S25 5G (256 GB) - Titanium Gray',
        sku: 'SKU-SAM-S25',
        quantity: 1,
        unitPrice: 87900,
        total: 87900,
      },
    ],
    createdAt: '2026-09-28',
  },
  {
    id: 'ord-1008',
    orderNumber: 'ORD-2026-0112',
    customerName: 'Ananya Roy',
    customerEmail: 'ananya.roy@yahoo.com',
    customerPhone: '+91 98300 22114',
    orderDate: '2026-09-28',
    status: 'PENDING',
    paymentStatus: 'PAID',
    totalAmount: 6498,
    warehouseId: 'wh-2',
    warehouseName: 'Mumbai Distribution Center',
    shippingAddress: {
      address: 'Flat 501, Lake View Residency, Powai',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400076',
    },
    items: [
      {
        productId: 'prod-109',
        productName: "Raymond Men's Premium Cotton Formal Shirt",
        sku: 'SKU-RAY-SHIRT-M',
        quantity: 2,
        unitPrice: 2499,
        total: 4998,
      },
      {
        productId: 'prod-112',
        productName: 'Bajaj DX-7 1000W Dry Iron',
        sku: 'SKU-BAJ-IRON-DX7',
        quantity: 1,
        unitPrice: 1500,
        total: 1500,
      },
    ],
    createdAt: '2026-09-28',
  },
  {
    id: 'ord-1009',
    orderNumber: 'ORD-2026-0125',
    customerName: 'Gaurav Kulkarni',
    customerEmail: 'gaurav.k@tcs.com',
    customerPhone: '+91 98451 99001',
    orderDate: '2026-09-23',
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    totalAmount: 149800,
    warehouseId: 'wh-1',
    warehouseName: 'Delhi Central Hub',
    shippingAddress: {
      address: 'Villa 14, Prestige Golfshire, Nandi Hills Road',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '562110',
    },
    items: [
      {
        productId: 'prod-101',
        productName: 'Apple iPhone 15 (128 GB) - Black',
        sku: 'SKU-APL-IP15',
        quantity: 2,
        unitPrice: 74900,
        total: 149800,
      },
    ],
    createdAt: '2026-09-23',
  },
  {
    id: 'ord-1010',
    orderNumber: 'ORD-2026-0136',
    customerName: 'Prakash Rao',
    customerEmail: 'prakash.rao@gmail.com',
    customerPhone: '+91 98490 88223',
    orderDate: '2026-09-22',
    status: 'CANCELLED',
    paymentStatus: 'REFUNDED',
    totalAmount: 7999,
    warehouseId: 'wh-4',
    warehouseName: 'Hyderabad Warehouse',
    shippingAddress: {
      address: 'Plot 10, Banjara Hills, Road 12',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500034',
    },
    items: [
      {
        productId: 'prod-105',
        productName: 'Philips Essential Air Fryer (4.1L, 1400W)',
        sku: 'SKU-PHL-AF9200',
        quantity: 1,
        unitPrice: 7999,
        total: 7999,
      },
    ],
    createdAt: '2026-09-22',
  },
  {
    id: 'ord-1011',
    orderNumber: 'ORD-2026-0144',
    customerName: 'Shalini Nair',
    customerEmail: 'shalini.nair@wipro.com',
    customerPhone: '+91 98455 12345',
    orderDate: '2026-09-25',
    status: 'SHIPPED',
    paymentStatus: 'PAID',
    totalAmount: 7598,
    warehouseId: 'wh-3',
    warehouseName: 'Bangalore Fulfillment Hub',
    shippingAddress: {
      address: 'B-604, Brigade Metropolis, Whitefield',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560048',
    },
    items: [
      {
        productId: 'prod-110',
        productName: "Levi's Men's 511 Slim Fit Jeans",
        sku: 'SKU-LEV-511-32',
        quantity: 2,
        unitPrice: 3799,
        total: 7598,
      },
    ],
    createdAt: '2026-09-25',
  },
  {
    id: 'ord-1012',
    orderNumber: 'ORD-2026-0158',
    customerName: 'Harish Mehta',
    customerEmail: 'hmehta@zenith.in',
    customerPhone: '+91 94140 33445',
    orderDate: '2026-09-27',
    status: 'CONFIRMED',
    paymentStatus: 'PAID',
    totalAmount: 6998,
    warehouseId: 'wh-6',
    warehouseName: 'Jaipur Regional Warehouse',
    shippingAddress: {
      address: '32, Civil Lines, Near Railway Station',
      city: 'Jaipur',
      state: 'Rajasthan',
      pincode: '302006',
    },
    items: [
      {
        productId: 'prod-111',
        productName: 'Havells Glaze 1200mm Ceiling Fan',
        sku: 'SKU-HAV-FAN1200',
        quantity: 2,
        unitPrice: 3499,
        total: 6998,
      },
    ],
    createdAt: '2026-09-27',
  },
  {
    id: 'ord-1013',
    orderNumber: 'ORD-2026-0167',
    customerName: 'Bhavna Chawla',
    customerEmail: 'bhavna.c@gmail.com',
    customerPhone: '+91 98102 77889',
    orderDate: '2026-09-28',
    status: 'PROCESSING',
    paymentStatus: 'PAID',
    totalAmount: 58999,
    warehouseId: 'wh-1',
    warehouseName: 'Delhi Central Hub',
    shippingAddress: {
      address: 'D-14, Hauz Khas Enclave',
      city: 'New Delhi',
      state: 'Delhi',
      pincode: '110016',
    },
    items: [
      {
        productId: 'prod-103',
        productName: 'Dell Inspiron 15 Laptop (Intel Core i5, 16GB)',
        sku: 'SKU-DEL-IN15',
        quantity: 1,
        unitPrice: 58999,
        total: 58999,
      },
    ],
    createdAt: '2026-09-28',
  },
  {
    id: 'ord-1014',
    orderNumber: 'ORD-2026-0179',
    customerName: 'Rajeev Menon',
    customerEmail: 'rajeev.menon@kpmg.com',
    customerPhone: '+91 98200 44556',
    orderDate: '2026-09-28',
    status: 'PACKED',
    paymentStatus: 'PAID',
    totalAmount: 41999,
    warehouseId: 'wh-2',
    warehouseName: 'Mumbai Distribution Center',
    shippingAddress: {
      address: 'Flat 11, Hiranandani Gardens, Powai',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400076',
    },
    items: [
      {
        productId: 'prod-106',
        productName: 'OnePlus 12R 5G (Cool Blue, 16GB RAM, 256GB)',
        sku: 'SKU-OP-12R',
        quantity: 1,
        unitPrice: 41999,
        total: 41999,
      },
    ],
    createdAt: '2026-09-28',
  },
  {
    id: 'ord-1015',
    orderNumber: 'ORD-2026-0188',
    customerName: 'Deepak Chopra',
    customerEmail: 'deepak.c@accenture.com',
    customerPhone: '+91 98452 66778',
    orderDate: '2026-09-29',
    status: 'PICKING',
    paymentStatus: 'PAID',
    totalAmount: 29900,
    warehouseId: 'wh-3',
    warehouseName: 'Bangalore Fulfillment Hub',
    shippingAddress: {
      address: 'Sobha Rose Apartments, Brookefield',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560037',
    },
    items: [
      {
        productId: 'prod-104',
        productName: 'Sony WH-1000XM5 Wireless Headphones',
        sku: 'SKU-SNY-1000XM5',
        quantity: 1,
        unitPrice: 29900,
        total: 29900,
      },
    ],
    createdAt: '2026-09-29',
  },
  {
    id: 'ord-1016',
    orderNumber: 'ORD-2026-0199',
    customerName: 'Sanjay Aggarwal',
    customerEmail: 'sanjay.aggarwal@gmail.com',
    customerPhone: '+91 98114 99887',
    orderDate: '2026-09-29',
    status: 'PENDING',
    paymentStatus: 'FAILED',
    totalAmount: 74900,
    warehouseId: 'wh-1',
    warehouseName: 'Delhi Central Hub',
    shippingAddress: {
      address: '22, Ring Road, Lajpat Nagar IV',
      city: 'New Delhi',
      state: 'Delhi',
      pincode: '110024',
    },
    items: [
      {
        productId: 'prod-101',
        productName: 'Apple iPhone 15 (128 GB) - Black',
        sku: 'SKU-APL-IP15',
        quantity: 1,
        unitPrice: 74900,
        total: 74900,
      },
    ],
    createdAt: '2026-09-29',
  },
];
