/**
 * Product Catalog Mock Data for Retail Inventory Management System (Project ID: P_022)
 * Phase 2B: Product Catalog Frontend UI
 * 
 * NOTE: This is TEMPORARY static mock data representing realistic Indian retail products
 * across categories such as Electronics, Accessories, Clothing, and Home Appliances.
 * Prices are in Indian Rupees (INR ₹).
 */

export const INITIAL_CATEGORIES = [
  {
    id: 'cat-1',
    name: 'Electronics',
    description: 'Smartphones, laptops, tablets, and computing hardware.',
    productCount: 4,
    status: 'Active',
    createdDate: '2026-01-15',
  },
  {
    id: 'cat-2',
    name: 'Accessories',
    description: 'Headphones, computer peripherals, cables, and wearables.',
    productCount: 3,
    status: 'Active',
    createdDate: '2026-01-18',
  },
  {
    id: 'cat-3',
    name: 'Clothing',
    description: 'Men, women, and kids apparel, casual wear, and formal shirts.',
    productCount: 2,
    status: 'Active',
    createdDate: '2026-02-01',
  },
  {
    id: 'cat-4',
    name: 'Home Appliances',
    description: 'Kitchen appliances, air fryers, ceiling fans, and utility gadgets.',
    productCount: 3,
    status: 'Active',
    createdDate: '2026-02-10',
  },
];

export const INITIAL_PRODUCTS = [
  {
    id: 'prod-101',
    sku: 'SKU-APL-IP15',
    name: 'Apple iPhone 15 (128 GB) - Black',
    category: 'Electronics',
    brand: 'Apple',
    description: 'Dynamic Island, 48MP main camera, A16 Bionic chip, USB-C connectivity, and aerospace-grade aluminum enclosure.',
    costPrice: 62000,
    sellingPrice: 74900,
    unit: 'Pieces',
    reorderLevel: 15,
    currentStock: 48,
    stockStatus: 'In Stock',
    status: 'Active',
    imageUrl: '',
    createdDate: '2026-02-10',
    updatedDate: '2026-09-22',
    warehouses: [
      { name: 'Delhi Central Hub', stock: 24, location: 'Shelf E-04' },
      { name: 'Mumbai Distribution Center', stock: 16, location: 'Shelf W-12' },
      { name: 'Bangalore Fulfillment Hub', stock: 8, location: 'Shelf S-02' },
    ],
  },
  {
    id: 'prod-102',
    sku: 'SKU-SAM-S25',
    name: 'Samsung Galaxy S25 5G (256 GB) - Titanium Gray',
    category: 'Electronics',
    brand: 'Samsung',
    description: 'Snapdragon 8 Elite chipset, Galaxy AI suite, 50MP triple camera system, and 120Hz Dynamic AMOLED display.',
    costPrice: 65000,
    sellingPrice: 79999,
    unit: 'Pieces',
    reorderLevel: 20,
    currentStock: 32,
    stockStatus: 'In Stock',
    status: 'Active',
    imageUrl: '',
    createdDate: '2026-02-14',
    updatedDate: '2026-09-24',
    warehouses: [
      { name: 'Delhi Central Hub', stock: 18, location: 'Shelf E-05' },
      { name: 'Mumbai Distribution Center', stock: 10, location: 'Shelf W-14' },
      { name: 'Bangalore Fulfillment Hub', stock: 4, location: 'Shelf S-03' },
    ],
  },
  {
    id: 'prod-103',
    sku: 'SKU-DEL-IN15',
    name: 'Dell Inspiron 15 Laptop (Intel Core i5, 16GB, 512GB SSD)',
    category: 'Electronics',
    brand: 'Dell',
    description: '15.6-inch FHD 120Hz display, Intel 13th Gen Core i5 processor, backlit keyboard, Windows 11 Home + MS Office.',
    costPrice: 46000,
    sellingPrice: 56990,
    unit: 'Pieces',
    reorderLevel: 10,
    currentStock: 7,
    stockStatus: 'Low Stock',
    status: 'Active',
    imageUrl: '',
    createdDate: '2026-02-20',
    updatedDate: '2026-09-25',
    warehouses: [
      { name: 'Delhi Central Hub', stock: 3, location: 'Shelf E-08' },
      { name: 'Mumbai Distribution Center', stock: 4, location: 'Shelf W-18' },
      { name: 'Bangalore Fulfillment Hub', stock: 0, location: 'Shelf S-05' },
    ],
  },
  {
    id: 'prod-104',
    sku: 'SKU-OP-12R',
    name: 'OnePlus 12R 5G (Cool Blue, 16GB RAM, 256GB Storage)',
    category: 'Electronics',
    brand: 'OnePlus',
    description: 'Snapdragon 8 Gen 2 processor, 100W SuperVOOC fast charging, 5500 mAh battery, and 4th Gen LTPO AMOLED screen.',
    costPrice: 33000,
    sellingPrice: 39999,
    unit: 'Pieces',
    reorderLevel: 12,
    currentStock: 0,
    stockStatus: 'Out of Stock',
    status: 'Active',
    imageUrl: '',
    createdDate: '2026-03-01',
    updatedDate: '2026-09-27',
    warehouses: [
      { name: 'Delhi Central Hub', stock: 0, location: 'Shelf E-10' },
      { name: 'Mumbai Distribution Center', stock: 0, location: 'Shelf W-20' },
      { name: 'Bangalore Fulfillment Hub', stock: 0, location: 'Shelf S-07' },
    ],
  },
  {
    id: 'prod-105',
    sku: 'SKU-SNY-1000XM5',
    name: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    category: 'Accessories',
    brand: 'Sony',
    description: 'Industry-leading Active Noise Cancellation with two processors and 8 microphones, 30-hour battery life, Multipoint connection.',
    costPrice: 22000,
    sellingPrice: 29990,
    unit: 'Pieces',
    reorderLevel: 12,
    currentStock: 25,
    stockStatus: 'In Stock',
    status: 'Active',
    imageUrl: '',
    createdDate: '2026-03-05',
    updatedDate: '2026-09-20',
    warehouses: [
      { name: 'Delhi Central Hub', stock: 12, location: 'Shelf A-01' },
      { name: 'Mumbai Distribution Center', stock: 8, location: 'Shelf A-06' },
      { name: 'Bangalore Fulfillment Hub', stock: 5, location: 'Shelf A-11' },
    ],
  },
  {
    id: 'prod-106',
    sku: 'SKU-LOG-MX3S',
    name: 'Logitech MX Master 3S Wireless Performance Mouse',
    category: 'Accessories',
    brand: 'Logitech',
    description: '8K DPI any-surface glass tracking, Quiet Clicks acoustic dampening, MagSpeed electromagnetic scrolling wheel.',
    costPrice: 6500,
    sellingPrice: 8995,
    unit: 'Pieces',
    reorderLevel: 15,
    currentStock: 9,
    stockStatus: 'Low Stock',
    status: 'Active',
    imageUrl: '',
    createdDate: '2026-03-12',
    updatedDate: '2026-09-26',
    warehouses: [
      { name: 'Delhi Central Hub', stock: 4, location: 'Shelf A-03' },
      { name: 'Mumbai Distribution Center', stock: 5, location: 'Shelf A-08' },
      { name: 'Bangalore Fulfillment Hub', stock: 0, location: 'Shelf A-14' },
    ],
  },
  {
    id: 'prod-107',
    sku: 'SKU-BOT-R450',
    name: 'boAt Rockerz 450 Bluetooth On-Ear Headphones',
    category: 'Accessories',
    brand: 'boAt',
    description: '40mm dynamic drivers, up to 15 hours playtime, plush ear cushions, integrated controls with dual connectivity.',
    costPrice: 900,
    sellingPrice: 1499,
    unit: 'Pieces',
    reorderLevel: 25,
    currentStock: 64,
    stockStatus: 'In Stock',
    status: 'Active',
    imageUrl: '',
    createdDate: '2026-03-15',
    updatedDate: '2026-09-18',
    warehouses: [
      { name: 'Delhi Central Hub', stock: 30, location: 'Shelf A-04' },
      { name: 'Mumbai Distribution Center', stock: 20, location: 'Shelf A-09' },
      { name: 'Bangalore Fulfillment Hub', stock: 14, location: 'Shelf A-15' },
    ],
  },
  {
    id: 'prod-108',
    sku: 'SKU-LEV-511SL',
    name: "Levi's 511 Slim Fit Men's Denim Jeans (Dark Indigo, 32W)",
    category: 'Clothing',
    brand: "Levi's",
    description: 'Cotton stretch denim, zip fly with button closure, classic five-pocket styling, engineered for comfort and modern fit.',
    costPrice: 1800,
    sellingPrice: 3299,
    unit: 'Pieces',
    reorderLevel: 20,
    currentStock: 42,
    stockStatus: 'In Stock',
    status: 'Active',
    imageUrl: '',
    createdDate: '2026-04-02',
    updatedDate: '2026-09-15',
    warehouses: [
      { name: 'Delhi Central Hub', stock: 20, location: 'Rack C-02' },
      { name: 'Mumbai Distribution Center', stock: 15, location: 'Rack C-05' },
      { name: 'Bangalore Fulfillment Hub', stock: 7, location: 'Rack C-08' },
    ],
  },
  {
    id: 'prod-109',
    sku: 'SKU-ALS-CSH01',
    name: "Allen Solly Men's Regular Fit Cotton Casual Shirt",
    category: 'Clothing',
    brand: 'Allen Solly',
    description: '100% premium combed cotton, button-down collar, curved hemline, breathable fabric ideal for corporate and casual occasions.',
    costPrice: 1100,
    sellingPrice: 1999,
    unit: 'Pieces',
    reorderLevel: 15,
    currentStock: 8,
    stockStatus: 'Low Stock',
    status: 'Inactive',
    imageUrl: '',
    createdDate: '2026-04-10',
    updatedDate: '2026-09-12',
    warehouses: [
      { name: 'Delhi Central Hub', stock: 5, location: 'Rack C-03' },
      { name: 'Mumbai Distribution Center', stock: 3, location: 'Rack C-06' },
      { name: 'Bangalore Fulfillment Hub', stock: 0, location: 'Rack C-09' },
    ],
  },
  {
    id: 'prod-110',
    sku: 'SKU-PHL-AF9200',
    name: 'Philips Essential Air Fryer (4.1L, 1400W Rapid Air Tech)',
    category: 'Home Appliances',
    brand: 'Philips',
    description: 'Rapid Air Technology with unique starfish bottom design, 90% less fat cooking, digital touch screen with 7 presets.',
    costPrice: 6800,
    sellingPrice: 9499,
    unit: 'Pieces',
    reorderLevel: 12,
    currentStock: 18,
    stockStatus: 'In Stock',
    status: 'Active',
    imageUrl: '',
    createdDate: '2026-04-20',
    updatedDate: '2026-09-26',
    warehouses: [
      { name: 'Delhi Central Hub', stock: 8, location: 'Bay H-01' },
      { name: 'Mumbai Distribution Center', stock: 6, location: 'Bay H-04' },
      { name: 'Bangalore Fulfillment Hub', stock: 4, location: 'Bay H-07' },
    ],
  },
  {
    id: 'prod-111',
    sku: 'SKU-BAJ-MIX500',
    name: 'Bajaj Rex 500W Mixer Grinder with 3 Stainless Steel Jars',
    category: 'Home Appliances',
    brand: 'Bajaj',
    description: '500-watt durable Titan motor, multi-functional blade system, rust-proof stainless steel jars with ergonomic easy-grip handles.',
    costPrice: 1850,
    sellingPrice: 2899,
    unit: 'Pieces',
    reorderLevel: 15,
    currentStock: 0,
    stockStatus: 'Out of Stock',
    status: 'Active',
    imageUrl: '',
    createdDate: '2026-05-02',
    updatedDate: '2026-09-21',
    warehouses: [
      { name: 'Delhi Central Hub', stock: 0, location: 'Bay H-02' },
      { name: 'Mumbai Distribution Center', stock: 0, location: 'Bay H-05' },
      { name: 'Bangalore Fulfillment Hub', stock: 0, location: 'Bay H-08' },
    ],
  },
  {
    id: 'prod-112',
    sku: 'SKU-HAV-CF1200',
    name: 'Havells Stealth Air 1200mm Premium Ceiling Fan - Pearl White',
    category: 'Home Appliances',
    brand: 'Havells',
    description: 'High air delivery of 280 m³/min, whisper-quiet aero-profile blades, 100% copper wire motor with dust resistant coating.',
    costPrice: 2600,
    sellingPrice: 3850,
    unit: 'Pieces',
    reorderLevel: 10,
    currentStock: 22,
    stockStatus: 'In Stock',
    status: 'Active',
    imageUrl: '',
    createdDate: '2026-05-15',
    updatedDate: '2026-09-25',
    warehouses: [
      { name: 'Delhi Central Hub', stock: 10, location: 'Bay H-03' },
      { name: 'Mumbai Distribution Center', stock: 8, location: 'Bay H-06' },
      { name: 'Bangalore Fulfillment Hub', stock: 4, location: 'Bay H-09' },
    ],
  },
];
