/**
 * Stock Movement Mock Data for Retail Inventory Management System (Project ID: P_022)
 * Phase 2D: Inventory Management Frontend UI
 * 
 * Movement Types:
 * - RECEIPT: Stock received from suppliers/procurement (+)
 * - SALE: Outbound fulfillment for retail customer orders (-)
 * - ADJUSTMENT: Physical audit reconciliations (+ or -)
 * - TRANSFER_IN: Inter-warehouse stock inbound receipt (+)
 * - TRANSFER_OUT: Inter-warehouse stock dispatch (-)
 * - RETURN: Customer return re-shelved (+)
 */

export const INITIAL_STOCK_MOVEMENTS = [
  {
    id: 'mov-1',
    inventoryId: 'inv-1',
    productName: 'Apple iPhone 15 (128 GB) - Black',
    sku: 'SKU-APL-IP15',
    warehouseName: 'Delhi Central Hub',
    warehouseCode: 'WH-DEL-001',
    type: 'RECEIPT',
    quantity: 50,
    reference: 'PO-2026-0012',
    performedBy: 'Amit Sharma',
    timestamp: '2026-09-28 14:30',
    notes: 'Bulk consignment received from Apple India Logistics distributor.',
  },
  {
    id: 'mov-2',
    inventoryId: 'inv-14',
    productName: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    sku: 'SKU-SNY-1000XM5',
    warehouseName: 'Bangalore Fulfillment Hub',
    warehouseCode: 'WH-BLR-001',
    type: 'TRANSFER_IN',
    quantity: 20,
    reference: 'TRF-2026-0007',
    performedBy: 'Karthik Raman',
    timestamp: '2026-09-28 11:15',
    notes: 'Stock received via inter-hub transfer from Delhi Central Hub.',
  },
  {
    id: 'mov-3',
    inventoryId: 'inv-17',
    productName: 'boAt Rockerz 450 Bluetooth On-Ear Headphones',
    sku: 'SKU-BOT-R450',
    warehouseName: 'Delhi Central Hub',
    warehouseCode: 'WH-DEL-001',
    type: 'RECEIPT',
    quantity: 100,
    reference: 'PO-2026-0015',
    performedBy: 'Amit Sharma',
    timestamp: '2026-09-28 09:40',
    notes: 'Seasonal replenishment order received from Imagine Marketing.',
  },
  {
    id: 'mov-4',
    inventoryId: 'inv-2',
    productName: 'Apple iPhone 15 (128 GB) - Black',
    sku: 'SKU-APL-IP15',
    warehouseName: 'Mumbai Distribution Center',
    warehouseCode: 'WH-MUM-001',
    type: 'SALE',
    quantity: -12,
    reference: 'ORD-2026-0048',
    performedBy: 'Priya Deshmukh',
    timestamp: '2026-09-27 16:50',
    notes: 'Dispatched for Western region enterprise retail orders.',
  },
  {
    id: 'mov-5',
    inventoryId: 'inv-7',
    productName: 'Dell Inspiron 15 Laptop (Intel Core i5, 16GB)',
    sku: 'SKU-DEL-IN15',
    warehouseName: 'Delhi Central Hub',
    warehouseCode: 'WH-DEL-001',
    type: 'ADJUSTMENT',
    quantity: 2,
    reference: 'ADJ-2026-0021',
    performedBy: 'Amit Sharma',
    timestamp: '2026-09-27 15:20',
    notes: 'Cycle count physical audit: 2 unopened units found in Bay E.',
  },
  {
    id: 'mov-6',
    inventoryId: 'inv-5',
    productName: 'Samsung Galaxy S25 5G (256 GB) - Titanium Gray',
    sku: 'SKU-SAM-S25',
    warehouseName: 'Mumbai Distribution Center',
    warehouseCode: 'WH-MUM-001',
    type: 'TRANSFER_IN',
    quantity: 15,
    reference: 'TRF-2026-0005',
    performedBy: 'Priya Deshmukh',
    timestamp: '2026-09-27 11:00',
    notes: 'Inter-hub rebalancing transfer arrived from Pune Warehouse.',
  },
  {
    id: 'mov-7',
    inventoryId: 'inv-12',
    productName: 'OnePlus 12R 5G (Cool Blue, 16GB RAM)',
    sku: 'SKU-OP-12R',
    warehouseName: 'Jaipur Regional Warehouse',
    warehouseCode: 'WH-JAI-001',
    type: 'RETURN',
    quantity: 1,
    reference: 'RET-2026-0003',
    performedBy: 'Vikram Singh Rathore',
    timestamp: '2026-09-26 17:10',
    notes: 'Customer returned unopened box; inspected and restored to inventory.',
  },
  {
    id: 'mov-8',
    inventoryId: 'inv-18',
    productName: 'boAt Rockerz 450 Bluetooth On-Ear Headphones',
    sku: 'SKU-BOT-R450',
    warehouseName: 'Hyderabad Warehouse',
    warehouseCode: 'WH-HYD-001',
    type: 'SALE',
    quantity: -14,
    reference: 'ORD-2026-0044',
    performedBy: 'Suresh Reddy',
    timestamp: '2026-09-26 14:05',
    notes: 'Bulk dispatch for Telangana campus retail outlets.',
  },
  {
    id: 'mov-9',
    inventoryId: 'inv-4',
    productName: 'Samsung Galaxy S25 5G (256 GB) - Titanium Gray',
    sku: 'SKU-SAM-S25',
    warehouseName: 'Delhi Central Hub',
    warehouseCode: 'WH-DEL-001',
    type: 'RECEIPT',
    quantity: 40,
    reference: 'PO-2026-0010',
    performedBy: 'Amit Sharma',
    timestamp: '2026-09-26 10:30',
    notes: 'Primary shipment received from Samsung India Noida warehouse.',
  },
  {
    id: 'mov-10',
    inventoryId: 'inv-19',
    productName: "Levi's 511 Slim Fit Men's Denim Jeans",
    sku: 'SKU-LEV-511SL',
    warehouseName: 'Mumbai Distribution Center',
    warehouseCode: 'WH-MUM-001',
    type: 'RECEIPT',
    quantity: 60,
    reference: 'PO-2026-0008',
    performedBy: 'Priya Deshmukh',
    timestamp: '2026-09-25 16:15',
    notes: 'Apparel autumn replenishment shipment processed.',
  },
  {
    id: 'mov-11',
    inventoryId: 'inv-16',
    productName: 'Logitech MX Master 3S Wireless Performance Mouse',
    sku: 'SKU-LOG-MX3S',
    warehouseName: 'Pune Regional Warehouse',
    warehouseCode: 'WH-PUN-001',
    type: 'SALE',
    quantity: -2,
    reference: 'ORD-2026-0039',
    performedBy: 'Rajesh Kulkarni',
    timestamp: '2026-09-25 13:45',
    notes: 'Outbound B2B fulfillment to IT park corporate client.',
  },
  {
    id: 'mov-12',
    inventoryId: 'inv-6',
    productName: 'Samsung Galaxy S25 5G (256 GB) - Titanium Gray',
    sku: 'SKU-SAM-S25',
    warehouseName: 'Hyderabad Warehouse',
    warehouseCode: 'WH-HYD-001',
    type: 'SALE',
    quantity: -4,
    reference: 'ORD-2026-0038',
    performedBy: 'Suresh Reddy',
    timestamp: '2026-09-25 11:20',
    notes: 'Retail order fulfillment dispatched via express delivery.',
  },
  {
    id: 'mov-13',
    inventoryId: 'inv-8',
    productName: 'Dell Inspiron 15 Laptop (Intel Core i5, 16GB)',
    sku: 'SKU-DEL-IN15',
    warehouseName: 'Pune Regional Warehouse',
    warehouseCode: 'WH-PUN-001',
    type: 'SALE',
    quantity: -3,
    reference: 'ORD-2026-0035',
    performedBy: 'Rajesh Kulkarni',
    timestamp: '2026-09-24 16:30',
    notes: 'Commercial procurement batch for regional consulting firm.',
  },
  {
    id: 'mov-14',
    inventoryId: 'inv-13',
    productName: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    sku: 'SKU-SNY-1000XM5',
    warehouseName: 'Delhi Central Hub',
    warehouseCode: 'WH-DEL-001',
    type: 'TRANSFER_OUT',
    quantity: -20,
    reference: 'TRF-2026-0007',
    performedBy: 'Amit Sharma',
    timestamp: '2026-09-24 10:15',
    notes: 'Outbound transfer dispatched to Bangalore Fulfillment Hub.',
  },
  {
    id: 'mov-15',
    inventoryId: 'inv-10',
    productName: 'OnePlus 12R 5G (Cool Blue, 16GB RAM)',
    sku: 'SKU-OP-12R',
    warehouseName: 'Delhi Central Hub',
    warehouseCode: 'WH-DEL-001',
    type: 'RECEIPT',
    quantity: 30,
    reference: 'PO-2026-0006',
    performedBy: 'Amit Sharma',
    timestamp: '2026-09-23 15:40',
    notes: 'New production stock arrived from manufacturer.',
  },
  {
    id: 'mov-16',
    inventoryId: 'inv-9',
    productName: 'Dell Inspiron 15 Laptop (Intel Core i5, 16GB)',
    sku: 'SKU-DEL-IN15',
    warehouseName: 'Bangalore Fulfillment Hub',
    warehouseCode: 'WH-BLR-001',
    type: 'SALE',
    quantity: -5,
    reference: 'ORD-2026-0031',
    performedBy: 'Karthik Raman',
    timestamp: '2026-09-22 17:00',
    notes: 'Stock depleted to 0 units following corporate bulk order.',
  },
  {
    id: 'mov-17',
    inventoryId: 'inv-21',
    productName: 'Philips Essential Air Fryer (4.1L, 1400W)',
    sku: 'SKU-PHL-AF9200',
    warehouseName: 'Delhi Central Hub',
    warehouseCode: 'WH-DEL-001',
    type: 'SALE',
    quantity: -15,
    reference: 'ORD-2026-0028',
    performedBy: 'Amit Sharma',
    timestamp: '2026-09-21 14:10',
    notes: 'Kitchen appliances weekend flash sale batch dispatched.',
  },
  {
    id: 'mov-18',
    inventoryId: 'inv-11',
    productName: 'OnePlus 12R 5G (Cool Blue, 16GB RAM)',
    sku: 'SKU-OP-12R',
    warehouseName: 'Mumbai Distribution Center',
    warehouseCode: 'WH-MUM-001',
    type: 'SALE',
    quantity: -8,
    reference: 'ORD-2026-0025',
    performedBy: 'Priya Deshmukh',
    timestamp: '2026-09-20 18:20',
    notes: 'Final stock units sold; reorder alert automatically triggered.',
  },
  {
    id: 'mov-19',
    inventoryId: 'inv-20',
    productName: "Allen Solly Men's Regular Fit Cotton Casual Shirt",
    sku: 'SKU-ALS-CSH01',
    warehouseName: 'Bangalore Fulfillment Hub',
    warehouseCode: 'WH-BLR-001',
    type: 'SALE',
    quantity: -10,
    reference: 'ORD-2026-0022',
    performedBy: 'Karthik Raman',
    timestamp: '2026-09-19 12:45',
    notes: 'Lifestyle retail chain regional consignment delivered.',
  },
  {
    id: 'mov-20',
    inventoryId: 'inv-22',
    productName: 'Philips Essential Air Fryer (4.1L, 1400W)',
    sku: 'SKU-PHL-AF9200',
    warehouseName: 'Mumbai Distribution Center',
    warehouseCode: 'WH-MUM-001',
    type: 'TRANSFER_IN',
    quantity: 10,
    reference: 'TRF-2026-0002',
    performedBy: 'Priya Deshmukh',
    timestamp: '2026-09-18 10:00',
    notes: 'Inter-warehouse safety buffer stock received from Delhi.',
  },
];
