/**
 * Supplier Mock Data for Retail Inventory Management System (Project ID: P_022)
 * Phase 2E: Supplier & Procurement Management
 * 
 * NOTE: Realistic Indian retail suppliers, distributors, and authorized vendors.
 */

export const INITIAL_SUPPLIERS = [
  {
    id: 'sup-1',
    supplierCode: 'SUP-DEL-001',
    name: 'Apex ElectroTech India Pvt Ltd',
    companyName: 'Apex ElectroTech Solutions Private Limited',
    category: 'Electronics',
    contactPerson: 'Rajesh Mehra',
    email: 'rajesh.mehra@apexelectro.in',
    phone: '+91 98110 44556',
    address: 'Plot 18, Block B-1, Mohan Cooperative Industrial Estate, Mathura Road',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110044',
    gstNumber: '07AAACA1234A1Z5',
    paymentTerms: 'Net 30',
    status: 'ACTIVE',
    productsSupplied: 6,
    createdAt: '2025-10-12',
  },
  {
    id: 'sup-2',
    supplierCode: 'SUP-MUM-002',
    name: 'Galaxy Distribution Networks',
    companyName: 'Galaxy Wholesale Telecom & Consumer Tech LLP',
    category: 'Electronics',
    contactPerson: 'Sunita Shetty',
    email: 'sunita.s@galaxydist.in',
    phone: '+91 98205 11223',
    address: 'Unit 402, Trade Star Building, Andheri-Kurla Road, Sakinaka, Andheri East',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400059',
    gstNumber: '27AABCG5678B1Z2',
    paymentTerms: 'Net 45',
    status: 'ACTIVE',
    productsSupplied: 5,
    createdAt: '2025-10-20',
  },
  {
    id: 'sup-3',
    supplierCode: 'SUP-BLR-003',
    name: 'Prime Computing Solutions',
    companyName: 'Prime Enterprise Peripherals & Systems Pvt Ltd',
    category: 'Electronics',
    contactPerson: 'Anand Venkatesh',
    email: 'anand.v@primecomputing.in',
    phone: '+91 98452 77889',
    address: 'Survey 14/2, Whitefield Main Road, EPIP Zone, Hoodi',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560066',
    gstNumber: '29AACCP9876C1Z8',
    paymentTerms: 'Net 30',
    status: 'ACTIVE',
    productsSupplied: 4,
    createdAt: '2025-11-05',
  },
  {
    id: 'sup-4',
    supplierCode: 'SUP-HYD-004',
    name: 'SoundWave Audio & Accessories',
    companyName: 'SoundWave Acoustic Devices India LLP',
    category: 'Accessories',
    contactPerson: 'Madhav Rao',
    email: 'm.rao@soundwaveindia.com',
    phone: '+91 98491 33445',
    address: 'Plot 72, Cyber Hills Colony, VIP Hills, Madhapur',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500081',
    gstNumber: '36AABCS4321D1Z1',
    paymentTerms: 'Net 15',
    status: 'ACTIVE',
    productsSupplied: 3,
    createdAt: '2025-11-18',
  },
  {
    id: 'sup-5',
    supplierCode: 'SUP-PUN-005',
    name: 'HomeComfort Appliances Ltd',
    companyName: 'HomeComfort Kitchen & Electricals Private Limited',
    category: 'Home Appliances',
    contactPerson: 'Sachin Patil',
    email: 'spatil@homecomfortindia.com',
    phone: '+91 97650 99887',
    address: 'Plot A-23, Phase 1, Hinjawadi Rajiv Gandhi Infotech Park',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411057',
    gstNumber: '27AABCH8765E1Z9',
    paymentTerms: 'Net 30',
    status: 'ACTIVE',
    productsSupplied: 4,
    createdAt: '2025-12-02',
  },
  {
    id: 'sup-6',
    supplierCode: 'SUP-SUR-006',
    name: 'Vantage Textile & Apparel Hub',
    companyName: 'Vantage Garment Manufacturers LLP',
    category: 'Clothing',
    contactPerson: 'Dinesh Patel',
    email: 'dinesh@vantagetextiles.in',
    phone: '+91 98251 66778',
    address: 'Ring Road Textile Market, Near Sahara Darwaja',
    city: 'Surat',
    state: 'Gujarat',
    pincode: '395002',
    gstNumber: '24AABCV3456F1Z3',
    paymentTerms: 'Advance',
    status: 'ACTIVE',
    productsSupplied: 2,
    createdAt: '2026-01-14',
  },
  {
    id: 'sup-7',
    supplierCode: 'SUP-DEL-007',
    name: 'Horizon Smart Peripherals',
    companyName: 'Horizon Accessories & Cables Pvt Ltd',
    category: 'Accessories',
    contactPerson: 'Pooja Kapoor',
    email: 'pooja.k@horizonperipherals.in',
    phone: '+91 98101 22334',
    address: 'Building 14, Nehru Place Commercial Complex',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110019',
    gstNumber: '07AABCH6543G1Z6',
    paymentTerms: 'Net 60',
    status: 'ON_HOLD',
    productsSupplied: 3,
    createdAt: '2026-02-01',
  },
  {
    id: 'sup-8',
    supplierCode: 'SUP-JAI-008',
    name: 'Bharat Electrical Goods LLP',
    companyName: 'Bharat Domestic Electrical Appliances LLP',
    category: 'Home Appliances',
    contactPerson: 'Kailash Choudhary',
    email: 'kailash@bharatelectrical.in',
    phone: '+91 94142 88990',
    address: 'Plot 45, Sitapura Industrial Area, Tonk Road',
    city: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302022',
    gstNumber: '08AABCB2198H1Z4',
    paymentTerms: 'Net 30',
    status: 'INACTIVE',
    productsSupplied: 2,
    createdAt: '2026-02-15',
  },
];
