/**
 * Warehouse Mock Data for Retail Inventory Management System (Project ID: P_022)
 * Phase 2C: Warehouse Management Frontend UI
 * 
 * NOTE: This is TEMPORARY static mock data representing realistic Indian regional
 * warehousing nodes, fulfillment centers, and distribution hubs.
 */

export const INITIAL_WAREHOUSES = [
  {
    id: 'wh-1',
    code: 'WH-DEL-001',
    name: 'Delhi Central Hub',
    address: 'Plot 42, Phase III, Okhla Industrial Area',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110020',
    managerName: 'Amit Sharma',
    managerEmail: 'amit.sharma@retailims.in',
    managerPhone: '+91 98112 34567',
    capacity: 50000,
    currentStock: 32450,
    status: 'ACTIVE',
    staffCount: 42,
    createdAt: '2025-11-10',
  },
  {
    id: 'wh-2',
    code: 'WH-MUM-001',
    name: 'Mumbai Distribution Center',
    address: 'Shed 12, Bhiwandi Logistics Corridor, NH-3',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '421302',
    managerName: 'Priya Deshmukh',
    managerEmail: 'priya.deshmukh@retailims.in',
    managerPhone: '+91 98201 98765',
    capacity: 45000,
    currentStock: 38200,
    status: 'ACTIVE',
    staffCount: 38,
    createdAt: '2025-11-15',
  },
  {
    id: 'wh-3',
    code: 'WH-BLR-001',
    name: 'Bangalore Fulfillment Hub',
    address: 'Survey 88, Hosur Road, Electronic City Phase II',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560100',
    managerName: 'Karthik Raman',
    managerEmail: 'karthik.raman@retailims.in',
    managerPhone: '+91 98450 11223',
    capacity: 40000,
    currentStock: 24600,
    status: 'ACTIVE',
    staffCount: 30,
    createdAt: '2025-12-01',
  },
  {
    id: 'wh-4',
    code: 'WH-HYD-001',
    name: 'Hyderabad Warehouse',
    address: 'Building B, Financial District Extension, Gachibowli',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500032',
    managerName: 'Suresh Reddy',
    managerEmail: 'suresh.reddy@retailims.in',
    managerPhone: '+91 98490 55443',
    capacity: 35000,
    currentStock: 18500,
    status: 'ACTIVE',
    staffCount: 26,
    createdAt: '2026-01-10',
  },
  {
    id: 'wh-5',
    code: 'WH-PUN-001',
    name: 'Pune Regional Warehouse',
    address: 'Gate 4, MIDC Industrial Area, Phase II, Chakan',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '410501',
    managerName: 'Rajesh Kulkarni',
    managerEmail: 'rajesh.kulkarni@retailims.in',
    managerPhone: '+91 97654 32109',
    capacity: 30000,
    currentStock: 27500,
    status: 'ACTIVE',
    staffCount: 22,
    createdAt: '2026-01-25',
  },
  {
    id: 'wh-6',
    code: 'WH-JAI-001',
    name: 'Jaipur Regional Warehouse',
    address: 'Sector 9, RIICO Industrial Zone, Sitapura',
    city: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302022',
    managerName: 'Vikram Singh Rathore',
    managerEmail: 'vikram.singh@retailims.in',
    managerPhone: '+91 94140 88776',
    capacity: 25000,
    currentStock: 8200,
    status: 'INACTIVE',
    staffCount: 14,
    createdAt: '2026-02-05',
  },
];

/**
 * Example inventory snapshot items for Warehouse Details view.
 * NOTE: This is MOCK ONLY for UI demonstration.
 * In later sprints, this section will be populated dynamically from:
 * Warehouse -> Inventory -> Product relationships.
 */
export const MOCK_WAREHOUSE_INVENTORY_ITEMS = [
  {
    id: 'inv-1',
    productName: 'Apple iPhone 15 (128 GB) - Black',
    sku: 'SKU-APL-IP15',
    category: 'Electronics',
    stock: 450,
    stockStatus: 'IN_STOCK',
  },
  {
    id: 'inv-2',
    productName: 'Samsung Galaxy S25 5G (256 GB) - Titanium Gray',
    sku: 'SKU-SAM-S25',
    category: 'Electronics',
    stock: 320,
    stockStatus: 'IN_STOCK',
  },
  {
    id: 'inv-3',
    productName: 'Dell Inspiron 15 Laptop (Intel Core i5, 16GB)',
    sku: 'SKU-DEL-IN15',
    category: 'Electronics',
    stock: 45,
    stockStatus: 'LOW_STOCK',
  },
  {
    id: 'inv-4',
    productName: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    sku: 'SKU-SNY-1000XM5',
    category: 'Accessories',
    stock: 120,
    stockStatus: 'IN_STOCK',
  },
  {
    id: 'inv-5',
    productName: 'Philips Essential Air Fryer (4.1L, 1400W)',
    sku: 'SKU-PHL-AF9200',
    category: 'Home Appliances',
    stock: 0,
    stockStatus: 'OUT_OF_STOCK',
  },
  {
    id: 'inv-6',
    productName: 'OnePlus 12R 5G (Cool Blue, 16GB RAM, 256GB)',
    sku: 'SKU-OP-12R',
    category: 'Electronics',
    stock: 85,
    stockStatus: 'LOW_STOCK',
  },
];
